metadata:
    sample_table: sample_table.csv
    output_dir: $HOME/hello_looper_results

implied_attributes:
    organism:
        human:
            genome: "hg38"
            macs_genome_size: "hs"
        mouse:
            genome: "mm10"
            macs_genome_size: "mm"

          
