protocol_mapping:
  PROTO1: other_pipeline1.py
  PROTO2: other_pipeline2.py 

pipelines:
  other_pipeline1.py:
    name: OTHER_PIPELINE1
    path: pipelines/other_pipeline1.py
    looper_args: True
    required_input_files: [read1]
    all_input_files: [read1, read2]
    ngs_input_files: [read1, read2]
    arguments:
      "--sample-name": sample_name
    outputs:
      output1: "other_pipeline1/{sample.sample_name}_{sample.Sample_geo_accession}_1.bw"
      output2:  "other_pipeline1/{sample.sample_name}_{sample.Sample_geo_accession}_2.bw"
    bioconductor:
      readFunName: readData
      readFunPath: readData.R
  other_pipeline2.py:
    name: OTHER_PIPELINE2
    path: pipelines/other_pipeline2.py
    looper_args: True
    required_input_files: [read1]
    all_input_files: [read1, read2]
    ngs_input_files: [read1, read2]
    arguments:
      "--sample-name": sample_name
    outputs:
      output1: "other_pipeline2/{sample.sample_name}_{sample.Sample_geo_accession}_1.bw"
      output2:  "other_pipeline2/{sample.sample_name}_{sample.Sample_geo_accession}_2.bw"
    bioconductor:
      readFunName: readData
      readFunPath: readData.R
