metadata:
  sample_table: sample_table.csv
  sample_subtable: sample_subtable.csv
  output_dir: $HOME/hello_looper_results
  pipeline_interfaces: [../pipeline/pipeline_interface.yaml]

derived_columns: [file]

data_sources:
  local_files: "../data/{identifier}{file_id}_data.txt"

