# Run gold standard samples through ATACseq pipeline.
name: project_name

metadata:
  sample_table: annotation_sheet.csv
  output_dir: ../output
  pipeline_interfaces: [pipeline_interface1.yaml, pipeline_interface2.yaml]
  
derived_attributes: [read1, read2]

data_sources:
  SRA_1: "{SRR}_1.fastq.gz"
  SRA_2: "{SRR}_2.fastq.gz"
