name: R-CMD-check

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{ matrix.r }})

    strategy:
      fail-fast: false
      matrix:
        r: ['release', 'devel']
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/xenial/latest

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("devtools")
          remotes::install_cran("covr")
        shell: Rscript {0}

      - name: Check package
        run: devtools::check()
        shell: Rscript {0}

      - name: Report test coverage
        run: covr::codecov()
        shell: Rscript {0}
